name: flutter_advanced_networkimage_without_svg
description: fork from flutter_advanced_networkimage,removed svg support.
version: 0.9.0
homepage: https://github.com/kooxiv/flutter_advanced_networkimage

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  path_provider: ^1.6.11
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: "^1.9.0"

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
